# Generated by Django 4.2.2 on 2023-06-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tlv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresario', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
